<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Buku;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'foto' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Tegal Laka-Laka: Dialek dan Identitas',
                'penulis' => 'Rahmat Haryono',
                'penerbit' => 'Tegal Literature Press',
                'jumlah_halaman' => 240,
                'sinopsis' => 'Buku ini membahas secara mendalam tentang keunikan dialek bahasa Tegal (Tegalan) dan bagaimana bahasa membentuk identitas masyarakatnya.',
                'bahasa' => 'Indonesia',
                'kategori' => 'BUDAYA',
                'isbn' => '978-602-1234-01-2',
                'tentang_penulis' => 'Rahmat Haryono adalah sosiolinguis asal Tegal.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Sejarah Pesisir Utara Jawa',
                'penulis' => 'Drs. Slamet Mulyono',
                'penerbit' => 'Mata Padi Press',
                'jumlah_halaman' => 310,
                'sinopsis' => 'Mengupas tuntas sejarah perdagangan, migrasi, dan pembentukan budaya kota-kota pelabuhan di pesisir utara Jawa, termasuk Tegal.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SEJARAH',
                'isbn' => '978-602-1234-02-9',
                'tentang_penulis' => 'Drs. Slamet Mulyono adalah sejarawan pesisir senior.',
                'status' => 'dipinjam',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Sajak Di Atas Kereta',
                'penulis' => 'Sitor Situmorang',
                'penerbit' => 'Pustaka Jaya',
                'jumlah_halaman' => 150,
                'sinopsis' => 'Kumpulan puisi romantis dan kontemplatif yang ditulis selama perjalanan kereta melintasi Jawa dan Sumatra.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SASTRA',
                'isbn' => '978-602-1234-03-6',
                'tentang_penulis' => 'Sitor Situmorang merupakan salah satu penyair angkatan 45 terkemuka.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Bumi Manusia',
                'penulis' => 'Pramoedya Ananta Toer',
                'penerbit' => 'Lentera Dipantara',
                'jumlah_halaman' => 538,
                'sinopsis' => 'Kisah romansa Minke dan Annelies dengan latar belakang pergerakan nasional awal abad ke-20 di bawah penjajahan kolonial.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SASTRA',
                'isbn' => '978-602-1234-04-3',
                'tentang_penulis' => 'Pramoedya Ananta Toer adalah sastrawan legendaris Indonesia yang beberapa kali dinominasikan untuk Nobel Sastra.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Warisan Kuliner Tegal',
                'penulis' => 'Fatimah Nurdin',
                'penerbit' => 'Kuliner Press',
                'jumlah_halaman' => 180,
                'sinopsis' => 'Resep rahasia dan kisah di balik lezatnya hidangan khas Tegal seperti Sauto, Nasi Bogana, dan Teh Poci.',
                'bahasa' => 'Indonesia',
                'kategori' => 'BUDAYA',
                'isbn' => '978-602-1234-05-0',
                'tentang_penulis' => 'Fatimah Nurdin adalah pakar kuliner tradisional Jawa Tengah.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1618666012174-83b441c0bc76?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Demokrasi Kekuasaan Desa',
                'penulis' => 'Prof. Dr. Supriyadi',
                'penerbit' => 'Sinar Grafika',
                'jumlah_halaman' => 280,
                'sinopsis' => 'Studi kritis tentang pergeseran kekuasaan, politik anggaran, dan implementasi demokrasi langsung di tingkat desa pasca UU Desa.',
                'bahasa' => 'Indonesia',
                'kategori' => 'POLITIK',
                'isbn' => '978-602-1234-06-7',
                'tentang_penulis' => 'Prof. Dr. Supriyadi adalah dosen Ilmu Politik di salah satu PTN terkemuka.',
                'status' => 'dipinjam',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Dunia Sophie',
                'penulis' => 'Jostein Gaarder',
                'penerbit' => 'Mizan',
                'jumlah_halaman' => 550,
                'sinopsis' => 'Novel filsafat yang mengajak pembaca bertualang menyusuri sejarah pemikiran barat melalui surat misterius untuk seorang gadis remaja bernama Sophie.',
                'bahasa' => 'Indonesia',
                'kategori' => 'FILOSOFI',
                'isbn' => '978-602-1234-07-4',
                'tentang_penulis' => 'Jostein Gaarder adalah novelis asal Norwegia yang piawai membumikan sejarah filsafat.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Masyarakat Tegal Urban',
                'penulis' => 'Anwar Halim',
                'penerbit' => 'Aksara Utama',
                'jumlah_halaman' => 220,
                'sinopsis' => 'Analisis sosiologis mengenai urbanisasi, tantangan ekonomi, dan pergeseran gaya hidup generasi muda di kota Tegal.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SOSIOLOGI',
                'isbn' => '978-602-1234-08-1',
                'tentang_penulis' => 'Anwar Halim merupakan sosiolog perkotaan lulusan Universitas Indonesia.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Visual Tegal Hari Ini',
                'penulis' => 'Aditya Rahman',
                'penerbit' => 'Seni Rupa Press',
                'jumlah_halaman' => 195,
                'sinopsis' => 'Kompilasi karya fotografi dan esai visual yang mendokumentasikan sudut-sudut estetis dan denyut kehidupan kota Tegal secara kontemporer.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SENI',
                'isbn' => '978-602-1234-09-8',
                'tentang_penulis' => 'Aditya Rahman adalah fotografer jalanan peraih berbagai penghargaan nasional.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=500',
                'judul' => 'The Future Future',
                'penulis' => 'Muhammad Farhan',
                'penerbit' => 'Futura Press',
                'jumlah_halaman' => 290,
                'sinopsis' => 'A comprehensive reflection on Tegal\'s literacy culture and its trajectory in the digital age.',
                'bahasa' => 'English',
                'kategori' => 'TEKNOLOGI',
                'isbn' => '978-602-1234-10-4',
                'tentang_penulis' => 'Muhammad Farhan adalah peneliti tren masa depan digital.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Echoes of Tegal',
                'penulis' => 'Dewi Lestari',
                'penerbit' => 'Bentang Pustaka',
                'jumlah_halaman' => 310,
                'sinopsis' => 'Tracing the oral history, poetry, and traditional narratives of the coastal society.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SASTRA',
                'isbn' => '978-602-1234-11-1',
                'tentang_penulis' => 'Dewi Lestari adalah novelis ternama Indonesia.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=500',
                'judul' => 'The Silent Archivist',
                'penulis' => 'Luthfi Ananda',
                'penerbit' => 'Tegal Literature Press',
                'jumlah_halaman' => 324,
                'sinopsis' => 'A tribute to local heroes who silently advanced community knowledge and education. Sebuah perjalanan mendalam menelusuri jejak-jejak literasi yang terlupakan di pesisir utara. Menghubungkan masa lalu yang sunyi dengan masa depan digital yang gegap gempita.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SEJARAH',
                'isbn' => '978-602-1234-56-7',
                'tentang_penulis' => 'Luthfi Ananda adalah seorang sejarawan dan penulis yang mendedikasikan karirnya untuk mendokumentasikan literatur pesisir Jawa Tengah.',
                'status' => 'ready',
            ],
            [
                'foto' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=500',
                'judul' => 'Modern Aesthetics',
                'penulis' => 'Rian Kusuma',
                'penerbit' => 'Design Indah',
                'jumlah_halaman' => 205,
                'sinopsis' => 'A design perspective on Tegal\'s colonial architecture and cultural evolution.',
                'bahasa' => 'Indonesia',
                'kategori' => 'SENI',
                'isbn' => '978-602-1234-13-5',
                'tentang_penulis' => 'Rian Kusuma adalah arsitek dan peneliti estetika modern.',
                'status' => 'ready',
            ]
        ];

        foreach ($books as $book) {
            Buku::create($book);
        }
    }
}
